### PR TITLE
[JENKINS-48412] Fix authorities retrieval for API Token

### PR DESCRIPTION
**Pull request by Wadeck**
- revealed by [#87](https://github.com/jenkinsci/github-oauth-plugin/pull/87)
- to reproduce you need to follow the guideline provided by @samrocketman in mentioned PR.
- does not seem to be a bug impacting user before the PR since some parts of code were not usable (`team` instead of `team.getName()`)

See [JENKINS-48412](https://issues.jenkins-ci.org/browse/JENKINS-48412).

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)

@reviewbybees but WIP until merge

### CODE REVIEW

**Comment by samrocketman** [comment]
I took the liberty of rebasing your change and resolved merge conflicts (there were not real conflicts so I'm not sure why `git` called it out as such).

**Comment by samrocketman** [comment]
This change also fixes [JENKINS-42421][JENKINS-42421].

[JENKINS-42421]: https://issues.jenkins-ci.org/browse/JENKINS-42421

**Comment by Wadeck** [comment]
Thank you @samrocketman, I put as resolved also the [JENKINS-48412](https://issues.jenkins-ci.org/browse/JENKINS-48412).

**Comment by Wadeck** [comment]
@samrocketman to be completely accurate, it's the #87 that solve the JENKINS-42421 ;-)

Thank you a lot for the amount of time you spend on open-source project like this one 👍

**Pull request merged**
