### PR TITLE
Update to modern versions of Jenkins

### PR DESCRIPTION
**Pull request by jglick**

### CODE REVIEW

**Comment by jglick** [comment]
Se #77.

**Review by Wadeck — APPROVED** [review]
:bee: Working fine with JEP-227

**Comment by Alien2150** [comment]
Any way to get it merged?

**Comment by jglick** [comment]
@samrocketman are you still active?

**Comment by Alien2150** [comment]
> @samrocketman are you still active?

Will it be compatible with the new xstream lib?

**Comment by samrocketman** [comment]
@jglick ; apologies for the delay.  I've been on a bit of a hiatus but I'm going to start ramping up contributions to Jenkins again.  I'll start by reviewing pull requests for github-oauth-plugin and try to address them (feedback or merge, etc)

**Review by basil — APPROVED** [review]

**Pull request merged**
