### PR TITLE
fix whitespace

### PR DESCRIPTION
**Pull request by jhoblitt**
* expand tabs into spaces
* fix inconsistent indenting
* minor formatting changes to improve "style" consistency
* remove trailing whitespace from end of line
* remove trailing newline from end of file

### CODE REVIEW

**Comment by jhoblitt** [comment]
@samrocketman Unfortunately, expanding just the tabs resulted in monster diff that would be a "rebase barrier" on its own.  It also broke mixed tab/whitespace indenting on successive lines and each file needed to be manually inspected..  Since I had to eyeball every line, I went ahead and tried to make the coding style a bit more consistent across files.

**Comment by skottler** [comment]
I generally support consistency in spacing style, but given massive changes in the history across lots of files like this it's probably better not to merge this. Doing so would make blame essentially useless because of the amount of rewriting that's going on here.

**Comment by jhoblitt** [comment]
Heyas @skottler!

In general, I agree but the mixed tabs/spaces in this plugin are pervasive enough that it complicates PR reviews and make it painful to edit files with an editor configured to highlights whitespace issues.  @samrocketman asked for a reformatting PR in https://github.com/jenkinsci/github-oauth-plugin/pull/39#commitcomment-12029115.

**Comment by samrocketman** [comment]
I don't think blame would be useless.  I think someone would use blame and see the whitespace commit.  Then use blame again on the commit before whitespace.  That would be what I would do.  At some point a change like this should be done otherwise it will just remain inconsistently formatted for the lifetime of the project.

**Comment by skottler** [comment]
That means that instead of being able to immediately understand the history of a file you have to turn it into a multi-step process, which is less than ideal for not a lot of immediate gain.

> At some point a change like this should be done otherwise it will just remain inconsistently formatted for the lifetime of the project.

The whitespace would progressively get fixed as the project changes over time.

Regardless I don't really work on the plugin anymore so if you think it's a good move then go for it.

**Comment by sirosen** [comment]
I was going to spout a lot of philosophy about whitespace, git-blame, git-log, separating formatting from functionality in commits, and so forth. Ultimately, no one wants to hear that.

What is relevant, however, is this:
I like this way of fixing the whitespace and I favor merging this PR. :+1:

**Comment by samrocketman** [comment]
I have performed a release.  Please rebase off of the latest master (or start over from the latest master).

**Comment by jhoblitt** [comment]
@samrocketman I've rebased the non-conflicting files and re-mangled files with changes.  That was significantly less fun the second time...

**Comment by samrocketman** [comment]
Thanks for your time.  It was necessary for me to get those other changes out the door for a release.  You won't have to do a second rebase because this change is prioritized next.  I'll test that this evening and if it all looks good then I'll merge.

**Comment by samrocketman** [comment]
Successfully reviewed and tested.  Thanks for taking the time to correct the white space.  I appreciate it.

**Comment by jhoblitt** [comment]
\o/

**Pull request merged**
