### PR TITLE
Prepare 0.25 release

### PR DESCRIPTION
**Pull request by samrocketman**
@i386 please review my release notes.

### CODE REVIEW

**Comment by i386** [comment]
LGTM!

**Comment by samrocketman** [comment]
Strange, I can't seem to get the darn tests to pass on cloudbees hosted CI.

**Comment by samrocketman** [comment]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Running org.jenkinsci.plugins.GithubAuthenticationTokenTest
Running org.jenkinsci.plugins.GithubAuthorizationStrategyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.196 sec - in org.jenkinsci.plugins.GithubAuthorizationStrategyTest
Running org.jenkinsci.plugins.GithubRequireOrganizationMembershipACLTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.192 sec - in org.jenkinsci.plugins.GithubAuthenticationTokenTest
Running org.jenkinsci.plugins.GithubLogoutActionTest

Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.198 sec - in org.jenkinsci.plugins.GithubRequireOrganizationMembershipACLTest
Running org.jenkinsci.plugins.api.GihubAPITest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.005 sec - in org.jenkinsci.plugins.api.GihubAPITest
Running org.jenkinsci.plugins.GithubSecurityRealmTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.922 sec - in org.jenkinsci.plugins.GithubLogoutActionTest
Running InjectedTest

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 81.543 sec - in org.jenkinsci.plugins.GithubSecurityRealmTest

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "jenkins.util.Timer [#5]"

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 164.193 sec - in InjectedTest

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "jenkins.util.Timer [#9]"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"

```

**Comment by samrocketman** [comment]
In any case, I've thoroughly tested this and tested the migrations from upgrading 0.24 -> 0.25.  I'm going to release now.

**Comment by samrocketman** [comment]
Released https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/github-oauth/0.25/github-oauth-0.25.hpi

**Comment by i386** [comment]
@samrocketman might be intermittent? 

thanks for the release. Maybe we should make the next one 1.0 to give it more legitimacy? Its widely used now

**Comment by samrocketman** [comment]
The next release can be 1.0.  There's one thing I want to do to the authorization before it hits 1.0.  I want to revamp it with discovered permissions akin to the matrix-based authorization but give users the ability to choose the exact permissions they want for the following GitHub users:

* Users with read access
* Users with write access
* Admin users

This way if a plugin adds custom permissions, the authorization strategy will support it.

**Comment by i386** [comment]
I'd like to get PR #75 in too

**Comment by oleg-nenashev** [comment]
@samrocketman @i386 
Minor comment: Update Manager grumbles about incompatible changes and recommends to check the changelog. But there is nothing inside. It would be useful to add the compatibility notes.

screen shot 2016-12-25 at 14 41 18

**Comment by oleg-nenashev** [comment]
After the update I've got the "API limit reached error". Likely the update is not responsible itself since there were many requests to github before the update

**Comment by samrocketman** [comment]
I'm not sure how to affect that warning.

**Comment by oleg-nenashev** [comment]
CC @daniel-beck since he was recently working in this area

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/github-oauth-plugin/blob/master/pom.xml#L150 is the responsible code. This actually declares that "When any version lower than 1.93 is installed, show a warning that the configuration format has changed on the upgrade screen".

**Comment by oleg-nenashev** [comment]
@daniel-beck  thanks!
Yep, it's reasonable. I've noticed this line, but somehow ignored it since the version was not even close to the current ones. My bad.

**Comment by samrocketman** [comment]
@daniel-beck Does this mean I should/could update `pom.xml` so that warning doesn't show?

**Pull request merged**
