### PR TITLE
[JENKINS-34835] Authorities from team slug

### PR DESCRIPTION
**Pull request by MancunianSam**
I've put the commits against [JENKINS-34835](https://issues.jenkins-ci.org/browse/JENKINS-34835) as the issue is still open. There was a PR #116 for this which gets the team based on the slug if it's set but the authorities list, which you can see if you go to /whoAmI, is still using the team name so if I set the team using org*slug in global security, I'm no longer allowed access.

### CODE REVIEW

**Comment by kumadee** [comment]
It will really great if this PR is merged and released with the new version of the plugin. I was facing this issue yesterday and figured out the root-cause by trial and error.

**Comment by samrocketman** [comment]
@kumadee apologies for the delay. I've been on a bit of a hiatus but I'm going to start ramping up contributions to Jenkins again. I'll start by reviewing pull requests for github-oauth-plugin and try to address them (feedback or merge, etc)

Thanks for contributing; this has been something on my TODO and I know users want this.

**Comment by MancunianSam** [comment]
@samrocketman @basil I've updated this branch with the latest from master and the checks are failing. I've looked at the logs and it looks like SIGTERM is being sent on each build and I can't see why. The Windows build has dependency errors but the dependencies it says are missing but which I can see in the repository. 

Do you know if there is a known issue with the builds failing like this or is this something I need to fix?

**Review by basil — APPROVED** [review]
Thanks for the PR!

Incremental build 0.35-rc429.8f7e6fa35ad6 is available for testing. The incremental build is available from: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/github-oauth/0.35-rc429.8f7e6fa35ad6/

@MancunianSam @apemberton @kumadee Can you please test the incremental build and confirm the issue is resolved? For instructions on how to install a custom build, see: https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation

**Comment by MancunianSam** [comment]
@basil I've tested the incremental build and the issue is fixed, thanks.

**Comment by basil** [comment]
Released in [0.35](https://github.com/jenkinsci/github-oauth-plugin/releases/tag/github-oauth-0.35).

**Comment by thatsmydoing** [comment]
I know the plugin is still 0.x and I should always read changelogs, but better messaging about this change would have been appreciated (I remember some plugin updates have big warnings on in the update screen). There's a potential to lock yourself out if you already had setup the authorization to work using team names instead of slugs.

**Comment by basil** [comment]
Hi @thatsmydoing, thanks for the note. I don't actually use this plugin or GitLab, and really only got involved with maintaining this plugin to deliver a fix required for the core Guava update, so it's possible I didn't fully understand the impact when merging and releasing this PR. Since you use this plugin, would you be willing to write a short blurb about upgrading? I would be happy to update the GitHub releases page with whatever you write.

**Comment by thatsmydoing** [comment]
Ah, I see. I was hoping for something like

**BREAKING CHANGE** group authorization changed from github team names to team slugs

When restricting access via groups (with for example, matrix-based security), and your github team names don't match team slugs (if they contain spaces for example), make sure to add another set of grants using the github team slug prior to upgrading otherwise you could potentially lock yourself out of Jenkins. After upgrading, it should be safe to remove the old github team name grants.

For example, if admin access is granted to the team "Jenkins Admin" with slug `jenkins-admin`, you might have `org*Jenkins Admin` as the group name currently. You would need to make sure to also have the same grants for `org*jenkins-admin` to ensure access after upgrading. After upgrading, it should be safe to remove the `org*Jenkins Admin` grant.

**Comment by basil** [comment]
Thank you @thatsmydoing. I updated [the release notes](https://github.com/jenkinsci/github-oauth-plugin/releases/tag/github-oauth-0.35) with the information you provided.

**Pull request merged**
