### PR TITLE
[JENKINS-28319] Store client secret encrypted

### PR DESCRIPTION
**Pull request by samrocketman**
This currently works when built with the following command.

```bash
mvn package -DskipTests=true
```

However, I'm having a hard time getting unit tests working.  Feedback would be much appreciated on how to mock this.

### CODE REVIEW

**Comment by samrocketman** [comment]
cc @daniel-beck

**Comment by johnpneumann** [comment]
@samrocketman - I have unit tests passing on mine. Would you prefer to merge mine into yours or should I do a new PR?

**Comment by johnpneumann** [comment]
scratch that. i'm having issues with mine still.

**Comment by samrocketman** [comment]
Closing in favor of #51.

**Pull request closed without merging**
