### PR TITLE
allow github oauth tokens to be used to access jenkins api

### PR DESCRIPTION
**Pull request by michaelneale**
as user/password for places where that is needed.

### CODE REVIEW

**Comment by samrocketman** [comment]
I'd like a few people to code review this pull request before it gets merged.

**Comment by michaelneale** [comment]
@samrocketman +1.

**Comment by samrocketman** [comment]
Can you give examples to places where a user/password is needed? It's not clear to me why this is desired.

**Comment by michaelneale** [comment]
@samrocketman interacting with the api - with this you can use oauth from github (alternative is to go to jenkins and create per user tokens as needed - I believe) but with this you can just delegate all auth to github.

**Comment by tfennelly** [comment]
LGTM insofar as I get it. I'm not so familiar with the Jenkins security API though (`SecurityContextHolder` etc).

I suppose it's difficult to write a test for this?

**Comment by michaelneale** [comment]
Yeah - I didn't see scaffolding to mock/simulate the GitHub api in place.

**Comment by michaelneale** [comment]
bump

**Comment by samrocketman** [comment]
Don't worry, I see it.  I'm leaving it open for people to get a chance to code review it.

**Comment by samrocketman** [comment]
I'll merge this the next chance I get.

**Comment by samrocketman** [comment]
I see no difference in the behavior of this plugin after merging and test this.  I still don't get what this does that the current implementation doesn't do.

**Comment by samrocketman** [comment]
Actually, I think I understand better what you meant by API.  You mean the Jenkins API, correct?

**Comment by samrocketman** [comment]
I can't seem to get this to work.  I've tried...

```
#using my GitHub credentials
curl -X POST http://localhost:8080/job/_jervis_generator/build --user "samrocketman:mypassword" --data-urlencode json='{"parameter": [{"name":"project", "value":"samrocketman/jervis"}]}'
#using my GitHub application token
curl -X POST http://localhost:8080/job/_jervis_generator/build --data "token=mytoken" --data-urlencode json='{"parameter": [{"name":"project", "value":"samrocketman/jervis"}]}'
```

Using the GitHub application token doesn't work at all.  When I use my GitHub username and password I get the following exception.

```
    <!DOCTYPE html><html><head resURL="/static/aa0c2d56">
    

    <title>Jenkins [Jenkins]</title><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/css/style.css" /><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/css/color.css" /><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/css/responsive-grid.css" /><link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/static/aa0c2d56/favicon.ico" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/aa0c2d56";</script><script src="/static/aa0c2d56/scripts/prototype.js" type="text/javascript"></script><script src="/static/aa0c2d56/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/aa0c2d56/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/aa0c2d56/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/aa0c2d56/scripts/yui/dom/dom-min.js"></script><script src="/static/aa0c2d56/scripts/yui/event/event-min.js"></script><script src="/static/aa0c2d56/scripts/yui/animation/animation-min.js"></script><script src="/static/aa0c2d56/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/aa0c2d56/scripts/yui/container/container-min.js"></script><script src="/static/aa0c2d56/scripts/yui/connection/connection-min.js"></script><script src="/static/aa0c2d56/scripts/yui/datasource/datasource-min.js"></script><script src="/static/aa0c2d56/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/aa0c2d56/scripts/yui/menu/menu-min.js"></script><script src="/static/aa0c2d56/scripts/yui/element/element-min.js"></script><script src="/static/aa0c2d56/scripts/yui/button/button-min.js"></script><script src="/static/aa0c2d56/scripts/yui/storage/storage-min.js"></script><script src="/static/aa0c2d56/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/aa0c2d56/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/scripts/yui/container/assets/container.css" /><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/scripts/yui/assets/skins/sam/skin.css" /><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/scripts/yui/container/assets/skins/sam/container.css" /><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/scripts/yui/button/assets/skins/sam/button.css" /><link rel="stylesheet" type="text/css" href="/static/aa0c2d56/scripts/yui/menu/assets/skins/sam/menu.css" /><link title="Jenkins" rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><script src="/static/aa0c2d56/scripts/yui/cookie/cookie-min.js"></script></head><body id="jenkins" data-version="jenkins-1.615" class="yui-skin-sam jenkins-1.615"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/"><img id="jenkins-head-icon" alt="title" src="/static/aa0c2d56/images/headshot.png" /><img id="jenkins-name-icon" height="34" alt="title" width="139" src="/static/aa0c2d56/images/title.png" /></a></div><div class="login"> <a href="/securityRealm/commenceLogin?from=%2Fjob%2F_jervis_generator%2Fbuild"><b>log in</b></a></div><div class="searchbox hidden-xs"><form style="position:relative;" name="search" action="/search/" class="no-json" method="get"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input id="search-box" placeholder="search" name="q" class="has-default-text" /> <a href="http://wiki.jenkins-ci.org/display/JENKINS/Search+Box"><img style="width: 16px; height: 16px; " class="icon-help icon-sm" src="/static/aa0c2d56/images/16x16/help.png" /></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/aa0c2d56/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/aa0c2d56/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a class="model-link inside" href="/">Jenkins</a></li><li class="children" href="/"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body"><div class="row"><div id="side-panel"><div id="side-panel-content"><div class="task"><a class="task-icon-link" href="http://jenkins-ci.org/"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-next icon-md" src="/static/aa0c2d56/images/24x24/next.png" /></a> <a class="task-link" href="http://jenkins-ci.org/">Jenkins project</a></div><div class="task"><a class="task-icon-link" href="http://issues.jenkins-ci.org/"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md" src="/static/aa0c2d56/images/24x24/gear2.png" /></a> <a class="task-link" href="http://issues.jenkins-ci.org/">Bug tracker</a></div><div class="task"><a class="task-icon-link" href="http://jenkins-ci.org/content/mailing-lists"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-search icon-md" src="/static/aa0c2d56/images/24x24/search.png" /></a> <a class="task-link" href="http://jenkins-ci.org/content/mailing-lists">Mailing Lists</a></div><div class="task"><a class="task-icon-link" href="https://twitter.com/jenkinsci"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-user icon-md" src="/static/aa0c2d56/images/24x24/user.png" /></a> <a class="task-link" href="https://twitter.com/jenkinsci">Twitter: @jenkinsci</a></div></div></div><div id="main-panel"><div id="main-panel-content"><a name="skip2content"></a><h1 style="text-align: center"><img height="179" width="154" src="/static/aa0c2d56/images/rage.png" /><span style="font-size:50px"> Oops!</span></h1><div id="error-description"><p>A problem occurred while processing the request.
        Please check <a href="https://issues.jenkins-ci.org/">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="http://jenkins-ci.org/content/mailing-lists">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
        at org.jenkinsci.plugins.GithubSecurityRealm$1.authenticate(GithubSecurityRealm.java:553)
        at jenkins.security.BasicHeaderRealPasswordAuthenticator.authenticate(BasicHeaderRealPasswordAuthenticator.java:55)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:79)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.kohsuke.github.Requester.parse(Requester.java:451)
        at org.kohsuke.github.Requester._to(Requester.java:224)
        at org.kohsuke.github.Requester.to(Requester.java:191)
        at org.kohsuke.github.GitHub.getMyself(GitHub.java:262)
        at org.kohsuke.github.GitHub.&lt;init>(GitHub.java:139)
        at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:195)
        at org.kohsuke.github.GitHub.connectUsingOAuth(GitHub.java:188)
        at org.jenkinsci.plugins.GithubAuthenticationToken.&lt;init>(GithubAuthenticationToken.java:98)
        at org.jenkinsci.plugins.GithubSecurityRealm$1.authenticate(GithubSecurityRealm.java:549)
        ... 38 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.kohsuke.github.Requester.parse(Requester.java:447)
        ... 46 more
</pre></div></div></div></div></div><div id="footer-container" class="hidden-xs"><div id="footer"><span class="page_generated">
          Page generated:
          Jul 11, 2015 11:40:22 AM</span><span class="rest_api"><a href="api/">REST API</a></span><span class="jenkins_ver"><a href="http://jenkins-ci.org/">Jenkins ver. 1.615</a></span><div id="l10n-dialog" class="dialog"></div><div id="l10n-footer" style="display:none; float:left"><a href="#" onclick="return showTranslationDialog();"><img src="/static/aa0c2d56/plugin/translation/flags.png" />
      Help us localize this page
    </a></div><script>var footer = document.getElementById('l10n-footer');
    var f = document.getElementById('footer');
    f.insertBefore(footer,f.firstChild);
    footer.style.display="block";

    var translation={}; 
    translation.bundles = "Prg1v/OOLLeIQAoGYAw+gCcc3uA9bnJXANM46Gwd86dzKKxI+YOGEN8CyEQIerDc8ZUPUIIY26/VQvD0SqXkaA/04NSHJzilacQ+ZDYix+sZEeqWg4OPscuOzLT2dQQoXzl7o0jStCLfLMeCnmTFSzVqVuZ4VIi18IMaNQAZJgKrri3gjatnm4l1CU0U/rssoAeg0DXeVe6K9Xy3t95b61qSCSD4Yc2tSJLek78zkLgDEfMtGqJGoq1wzxV/b5Iucnlz05g8bqe6gY+YesGaVVZXFohnCb91zE4blszjS+B8ENCy/UhrevPyEe/Q+AoE1DQh7sIL3VyjrbMTb/bkA3p2Aapp2FrjTZBnkwofqNLUEtHuaxhXOjYzuZiBHrGlQxm2ikJeVapGujhZC9SFD3waVzRUwaLQnN32H6mGOx/mXj500Eb1Z/j2ULUiNkNr1MJAqn2281pMiuIWaMoLntaQIwWn3YJyO6aiUI33qSO/fPMaMaYWoygT0ucqskt5";
    translation.detectedLocale = "";

    function showTranslationDialog() {
      if(!translation.launchDialog)
        loadScript("/static/aa0c2d56/plugin/translation/dialog.js");
      else
        translation.launchDialog();
      return false; 
    }</script></div></div></body></html>
```

Please note:

```
java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
        at org.jenkinsci.plugins.GithubSecurityRealm$1.authenticate(GithubSecurityRealm.java:553)
        at jenkins.security.BasicHeaderRealPasswordAuthenticator.authenticate(BasicHeaderRealPasswordAuthenticator.java:55)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:79)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.kohsuke.github.Requester.parse(Requester.java:451)
        at org.kohsuke.github.Requester._to(Requester.java:224)
        at org.kohsuke.github.Requester.to(Requester.java:191)
        at org.kohsuke.github.GitHub.getMyself(GitHub.java:262)
        at org.kohsuke.github.GitHub.&lt;init>(GitHub.java:139)
        at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:195)
        at org.kohsuke.github.GitHub.connectUsingOAuth(GitHub.java:188)
        at org.jenkinsci.plugins.GithubAuthenticationToken.&lt;init>(GithubAuthenticationToken.java:98)
        at org.jenkinsci.plugins.GithubSecurityRealm$1.authenticate(GithubSecurityRealm.java:549)
        ... 38 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.kohsuke.github.Requester.parse(Requester.java:447)
        ... 46 more
```

I generated a token with only `read:org` permissions.  Since it's trying to access the user api perhaps I need user permissions as well.

**Comment by samrocketman** [comment]
Still having a hard time testing this.  Here's basically the steps I've done on Ubuntu 14.04.2 LTS.

I automatically provisioned Jenkins using [`jenkins-bootstrap-jervis`][jbj].

```bash
cd ~/git/github/
git clone git@github.com:samrocketman/jenkins-bootstrap-jervis.git
cd jenkins-bootstrap-jervis
./jervis_bootstrap.sh
```

Now that Jenkins is up and running I built and installed the github-oauth plugin.

```bash
#downloaded Oracle Java 1.6
export JAVA_HOME="/home/sam/src/java/jdk1.6.0_45/"
export PATH="${JAVA_HOME}/bin:${PATH}"
#download Apache maven 3.2.5
export PATH="/home/sam/src/maven/apache-maven-3.2.5/bin:${PATH}"
#clone the latest master of github-oauth plugin
cd ~/git/github/
git clone git@github.com:jenkinsci/github-oauth-plugin.git
cd github-oauth-plugin
#merge pull request 37
git ls-remote origin | grep 37
git fetch origin refs/pull/37/head
git merge --no-ff FETCH_HEAD 
#build the plugin
mvn test && mvn package
#Install the newly built plugin.
cd ~/git/github/jenkins-bootstrap-jervis
./scripts/provision_jenkins.sh install-plugins ~/git/github/github-oauth-plugin/target/github-oauth.hpi
#Restart jenkins
./scripts/provision_jenkins.sh restart
```

I visited `https://localhost:8080/` and configured Global Security.  I set the _Security Realm_ to GitHub Authentication Plugin.  I also configured _Authorization_ to Project-based Matrix Authorization Strategy.

In the global project-based matrix authorization strategy settings I configured the following users.

* `Anonymous`: Overall read permissions
* `samrocketman`: Overall Administer.

I then executed.

```bash
curl -X POST http://localhost:8080/job/_jervis_generator/build --user "samrocketman:myGitHubPassword" --data-urlencode json='{"parameter": [{"name":"project", "value":"samrocketman/jervis"}]}'
```

[jbj]: https://github.com/samrocketman/jenkins-bootstrap-jervis

**Comment by samrocketman** [comment]
I even gave `read:org,user` permissions to the global configurations settings for the security realm.  Still get the same error.  I would expect that this _should_ work with just `read:org`.  As of right now it doesn't work at all for me.

**Comment by samrocketman** [comment]
I finally figured it out.

1. Generate a _Personal Access Token_ and give it only `read:org` scope.
2. Use a username and GitHub personal access token to authenticate with the Jenkins API.

```bash
curl -X POST http://localhost:8080/job/_jervis_generator/build --user "samrocketman:myGitHubPersonalAccessToken" --data-urlencode json='{"parameter": [{"name":"project", "value":"samrocketman/jervis"}]}'
```

**Comment by samrocketman** [comment]
In the future, I would really appreciate if you could give me more information with how I can test a change you're making.  It would make my life easier.  In any case, this is a really neat change.  Great job!

**Comment by michaelneale** [comment]
Thanks @samrocketman. Sorry my fault. 1) I have used github 2FA for a long time so it never occurred to me to try the normal password (ie I have used personal access tokens since forever) - my mistake. 2) I was lazing around this weekend feeling the effects of a cold so didn't see your trials. I should have put an example in of what I mean to save you working it out in the end!

Sorry about that - but thanks again for merging. It is a pretty neat change (not sure how people did api access otherwise, perhaps they don't like this...), and you get to use github to audit and control all access.

**Comment by samrocketman** [comment]
I really like the change.  To access the API one would typically generate their own Jenkins tokens or make use of the SSH private/public key pair to authenticate with Jenkins API.  This has given a path forward for being a fix for another issue in JIRA: [JENKINS-17539][JENKINS-17539].  Thanks again for this neat contribution.

[JENKINS-17539]: https://issues.jenkins-ci.org/browse/JENKINS-17539

**Comment by michaelneale** [comment]
NP. FYI this has been in use in production for some time at http://ambiata.com/ so it works quite well (it goes as far as even using github auth to have ssh slaves self register (jnlp wasn't quite right in this case) with the master - so very convenient.  Wiki is down but I gather you just did a release?

**Comment by samrocketman** [comment]
Correct, I did a release earlier today.  You can [download it at Jenkins maven][jm].

[jm]: http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/github-oauth/0.21.1/

**Comment by michaelneale** [comment]
thanks @samrocketman

**Pull request merged**
