### PR TITLE
Fixed JENKINS-33883 by allowing .*/cc.xml instead of only root one.

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by samrocketman** [comment]
I will review this, test, and merge before the next release.

**Comment by ssbarnea** [comment]
Thanks. I am already using it in production since two weeks ago and didnt had any problems.

Still, you will observe that is quite inconvenient to use a cc.xml with github organization plugin because of the multiple cc.xml files. Also the published job names are the branch names, so you may not be able to distinguish between jobs. Still this is another issue that has nothing to do with the auhentication plugin.

**Comment by samrocketman** [comment]
No sure I fully comprehend because I don't use cruise control.  However, if after testing it doesn't affect the functionality of the plugin in a negative way and it helps you out; then I see no reason not to include it.

**Comment by samrocketman** [comment]
Released 0.24.  It should be available in about 8 hrs in the update center.  Or download it at https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/github-oauth/0.24/github-oauth-0.24.hpi

**Pull request merged**
