### PR TITLE
Fix Java 7 compatibility when running unit tests.

### PR DESCRIPTION
**Pull request by samrocketman**
Unit tests now work with Java 7.  Code review and testing would be much appreciated.

* relates to [JENKINS-21252][JENKINS-21252]
* fixes [JENKINS-29373]

[JENKINS-21252]: https://issues.jenkins-ci.org/browse/JENKINS-21252
[JENKINS-29373]: https://issues.jenkins-ci.org/browse/JENKINS-29373

### CODE REVIEW

**Comment by samrocketman** [comment]
Code review, please.

**Comment by samrocketman** [comment]
@cloudbeesci peer review, please.

**Comment by daniel-beck** [comment]
Wouldn't 1.532 or so suffice?

**Comment by samrocketman** [comment]
@daniel-beck I can test with 1.532.  I chose 1.586 because that was the mentioned minimum version in [JENKINS-21252][JENKINS-21252].  Here's a quote.

> Jenkins has been updated to use JNA 4.1: [JENKINS-24521][JENKINS-24521]
Please try again, since this fixes many native library issues.
The fix will be in Jenkins 1.586 and higher.

What makes you choose specifically 1.532?

[JENKINS-21252]: https://issues.jenkins-ci.org/browse/JENKINS-21252
[JENKINS-24521]: https://issues.jenkins-ci.org/browse/JENKINS-24521

**Comment by samrocketman** [comment]
@daniel-beck I tested with 1.532.  It failed to test with Java 7.

cc @jcarsique code review, please.  I recall we had a conversation about Java 7 compatibility.

**Pull request merged**
