### PR TITLE
Minimal fix for [JENKINS-54031] GitHub OAuth plugin fails with Jenkins 2.146

### PR DESCRIPTION
**Pull request by kfarnung**
https://issues.jenkins-ci.org/browse/JENKINS-54031

While testing out #101 it seems like there are a lot of changes to land quickly and safely.  This patch aims to make a surgical fix without any cleanup or logic flow changes.

### CODE REVIEW

**Comment by nickmccally** [comment]
Thank you so much. I have compiled and tested - it has fixed the jenkins github oauth issue for my team.

**Comment by conf** [comment]
Any update on this? This is blocking us from upgrade to the most recent Jenkins version :(

**Comment by juliangrosshauser** [comment]
This change fixed the permission problems for my team. Thank you!

**Comment by joppa27** [comment]
can someone @jenkinsci/code-reviewers please take a look at this change?

**Comment by stfp** [comment]
@samrocketman just want to bump this back on your radar... thanks!

**Comment by samrocketman** [comment]
Sorry for taking so long.  I'm in the midst of moving cross country so my volunteer development time is suffering.  In any case, I just release 0.31 which includes this fix.

**Comment by stfp** [comment]
Many thanks - we all appreciate your time and effort! And good luck with the move 🚚

**Comment by samrocketman** [comment]
There was a lot of git spaghetti in this release :joy: https://github.com/jenkinsci/github-oauth-plugin/network

**Pull request merged**
